const Status = {
  UNVERIFIED: 'UNVERIFIED',
  REVIEW_PENDING: 'REVIEW_PENDING',
  RETRY_REQUESTED: 'RETRY_REQUESTED',
  DOCUMENT_REQUESTED: 'DOCUMENT_REQUESTED',
  SUSPENDED: 'SUSPENDED',
  VERIFIED: 'VERIFIED',
  RETRY: 'RETRY',
  BANK_ADDED: 'BANK_ADDED',
  CARD_ADDED: 'CARD_ADDED',
};

export default Status;
