export const SET_NET_INFO = 'SET_NET_INFO';

export const PRESENT_LOADER = 'PRESENT_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const PRESENT_MODAL = 'PRESENT_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const RESET_STORE = 'RESET_STORE';

export const SET_TOKEN = 'SET_TOKEN';
export const RESET_TOKEN = 'RESET_TOKEN';
export const REFRESH_ACCESS_TOKEN = 'REFRESH_ACCESS_TOKEN';

export const REFRESH_TOKEN_POST_API_REQUEST = 'REFRESH_TOKEN_POST_API_REQUEST';
export const REFRESH_TOKEN_POST_API_SUCCESS = 'REFRESH_TOKEN_POST_API_SUCCESS';
export const REFRESH_TOKEN_POST_API_FAILURE = 'REFRESH_TOKEN_POST_API_FAILURE';

// actions for users
export const AUTH_TOKEN = 'AUTH_TOKEN';
export const SET_ERROR = 'SET_ERROR';
export const RESET_ERROR = 'RESET_ERROR';
export const SET_SUCCESS = 'SET_SUCCESS';
export const SET_USER = 'SET_USER';
export const RESET_AUTH = 'RESET_AUTH';
export const SET_PROFILE_COMPLETE_STATUS = 'SET_PROFILE_COMPLETE_STATUS';

export const LOGIN_POST_API_REQUEST = 'LOGIN_POST_API_REQUEST';
export const LOGIN_POST_API_SUCCESS = 'LOGIN_POST_API_SUCCESS';
export const LOGIN_POST_API_FAILURE = 'LOGIN_POST_API_FAILURE';

export const SIGNUP_POST_API_REQUEST = 'SIGNUP_POST_API_REQUEST';
export const SIGNUP_POST_API_SUCCESS = 'SIGNUP_POST_API_SUCCESS';
export const SIGNUP_POST_API_FAILURE = 'SIGNUP_POST_API_FAILURE';

export const FORGOT_PASSWORD_POST_API_REQUEST =
  'FORGOT_PASSWORD_POST_API_REQUEST';
export const FORGOT_PASSWORD_POST_API_SUCCESS =
  'FORGOT_PASSWORD_POST_API_SUCCESS';
export const FORGOT_PASSWORD_POST_API_FAILURE =
  'FORGOT_PASSWORD_POST_API_FAILURE';

export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';

// user details actions
export const GET_CURRENT_USER_DETAILS = 'GET_CURRENT_USER_DETAILS';

// Action Required for Transaction Flow
export const CREATE_TRANSACTION_DATA = 'CREATE_TRANSACTION_DATA';
export const CLEAR_TRANSACTION_DATA = 'CLEAR_TRANSACTION_DATA';

export const ON_REQUEST_DEVICE_VERIFICATION_CODE =
  'ON_REQUEST_DEVICE_VERIFICATION_CODE';

export const IS_LOGIN_FORM_CALCULATOR = 'IS_LOGIN_FORM_CALCULATOR';

export const SHOW_TOAST = 'SHOW_TOAST';
export const HIDE_TOAST = 'HIDE_TOAST';
